version: "3.3"
services:

  # ********************************   cluster1  ********************************
  # cluster1 app 1
  cluster1_app:
    #image: wisrovi/tfm_2022:v2-app-dev
    image: wisrovi/tfm_2022:v2-app-prod
    environment:
      - CLUSTER_NAME=cluster1
    volumes:
      - ./log:/log
    ports:
      - "10110:80"
    depends_on:
      - cluster1_clasificador

  # cluster1 clasificador
  cluster1_clasificador:
    image: wisrovi/tfm_2022:v2-model
    volumes:
      - ./log:/log
    environment:
      - CLUSTER_NAME=cluster1
    depends_on:
      - redis

  # ********************************   https  ********************************
  nginx_https:
    image: nginx:latest
    links:
      - cluster1_app
    volumes:
        - ./nginx/https/:/etc/nginx/conf.d/
        - ./nginx/https/ssl/:/etc/ssl/certs
    ports:
      - "10111:443"

    restart: always


  redis:
    image: redislabs/redismod
    #ports:
    #  - "6379:6379"
    environment:
      - SO=docker
    volumes:
      - ./cache_redis:/data
    command: --dir /data --loadmodule /usr/lib/redis/modules/redistimeseries.so

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - "8081:8081"
    depends_on:
      - redis
